name: 🧹 Code Layout

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - release-**
      - queued_ltr_backports
  pull_request:

permissions:
  contents: read

env:
  DOXYGEN_VERSION: 1.9.8

jobs:

  spell_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Requirements
        run: |
          sudo apt install -y \
              expect \
              silversearcher-ag
      - uses: tj-actions/changed-files@v42
        id: changed_files
        with:
          separator: ' '
        env:
          ALL_CHANGED_FILES: ${{ steps.changed_files.outputs.all_changed_files }}
      - name: Spell Test
        run: echo "$ALL_CHANGED_FILES" | ./scripts/spell_check/check_spelling.sh
